networks:
  prod:

services:
  backend:
    build: ./backend
    container_name: quiz-api
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://quizuser:secretpassword@db:5432/battlequiz
    depends_on:
      - db
    networks:
      - prod

  frontend:
    build: ./frontend
    container_name: quiz-client
    depends_on:
      - backend
    networks:
      - prod

  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prod
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - prod

volumes:
  postgres_data:
