"""First migration

Revision ID: f0ecb96cf756
Revises: 3f38dab526ab
Create Date: 2025-04-27 17:02:45.498576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ecb96cf756'
down_revision = '3f38dab526ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_item', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
